export enum PROVIDERS {
  USER_REPOSITORY = 'USER_REPOSITORY',
  MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY',
  DATABASE_MAIN_CONNECTION = 'DATABASE_MAIN_CONNECTION',
  CACHE_MAIN_CONNECTION = 'CACHE_MAIN_CONNECTION',
}
